version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  redis-data: 